---90-degree turn detection table (simplified)
---Each entry maps (rail_type, placement_direction) to exactly ONE turn position
---Turns are always a→b→b→a pattern from cardinal to cardinal
---Generated by extract-turn-table.lua
---@type table<string, table<defines.direction, {position: string, from_cardinal: defines.direction, to_cardinal: defines.direction, verify_forward: {end_dir: defines.direction, turn_dir: number, count: number}, verify_back: {end_dir: defines.direction, turn_dir: number, count: number}}>>

require("polyfill")

return {
   ["curved-rail-a"] = {
      [defines.direction.north] = {
         position = "bottom", -- east-to-south
         from_cardinal = defines.direction.east,
         to_cardinal = defines.direction.south,
         verify_forward = { end_dir = defines.direction.south, turn_dir = 1, count = 0 },
         verify_back = { end_dir = defines.direction.northnorthwest, turn_dir = -1, count = 3 },
      },
      [defines.direction.northeast] = {
         position = "bottom", -- west-to-south
         from_cardinal = defines.direction.west,
         to_cardinal = defines.direction.south,
         verify_forward = { end_dir = defines.direction.south, turn_dir = -1, count = 0 },
         verify_back = { end_dir = defines.direction.northnortheast, turn_dir = 1, count = 3 },
      },
      [defines.direction.east] = {
         position = "bottom", -- east-to-north
         from_cardinal = defines.direction.east,
         to_cardinal = defines.direction.north,
         verify_forward = { end_dir = defines.direction.eastnortheast, turn_dir = -1, count = 3 },
         verify_back = { end_dir = defines.direction.west, turn_dir = 1, count = 0 },
      },
      [defines.direction.southeast] = {
         position = "top", -- east-to-south
         from_cardinal = defines.direction.east,
         to_cardinal = defines.direction.south,
         verify_forward = { end_dir = defines.direction.eastsoutheast, turn_dir = 1, count = 3 },
         verify_back = { end_dir = defines.direction.west, turn_dir = -1, count = 0 },
      },
      [defines.direction.south] = {
         position = "top", -- west-to-north
         from_cardinal = defines.direction.west,
         to_cardinal = defines.direction.north,
         verify_forward = { end_dir = defines.direction.north, turn_dir = 1, count = 0 },
         verify_back = { end_dir = defines.direction.southsoutheast, turn_dir = -1, count = 3 },
      },
      [defines.direction.southwest] = {
         position = "top", -- east-to-north
         from_cardinal = defines.direction.east,
         to_cardinal = defines.direction.north,
         verify_forward = { end_dir = defines.direction.north, turn_dir = -1, count = 0 },
         verify_back = { end_dir = defines.direction.southsouthwest, turn_dir = 1, count = 3 },
      },
      [defines.direction.west] = {
         position = "top", -- west-to-south
         from_cardinal = defines.direction.west,
         to_cardinal = defines.direction.south,
         verify_forward = { end_dir = defines.direction.westsouthwest, turn_dir = -1, count = 3 },
         verify_back = { end_dir = defines.direction.east, turn_dir = 1, count = 0 },
      },
      [defines.direction.northwest] = {
         position = "bottom", -- west-to-north
         from_cardinal = defines.direction.west,
         to_cardinal = defines.direction.north,
         verify_forward = { end_dir = defines.direction.westnorthwest, turn_dir = 1, count = 3 },
         verify_back = { end_dir = defines.direction.east, turn_dir = -1, count = 0 },
      },
   },

   ["curved-rail-b"] = {
      [defines.direction.north] = {
         position = "lower-half", -- east-to-south
         from_cardinal = defines.direction.east,
         to_cardinal = defines.direction.south,
         verify_forward = { end_dir = defines.direction.southsoutheast, turn_dir = 1, count = 1 },
         verify_back = { end_dir = defines.direction.northwest, turn_dir = -1, count = 2 },
      },
      [defines.direction.northeast] = {
         position = "lower-half", -- west-to-south
         from_cardinal = defines.direction.west,
         to_cardinal = defines.direction.south,
         verify_forward = { end_dir = defines.direction.southsouthwest, turn_dir = -1, count = 1 },
         verify_back = { end_dir = defines.direction.northeast, turn_dir = 1, count = 2 },
      },
      [defines.direction.east] = {
         position = "lower-half", -- east-to-north
         from_cardinal = defines.direction.east,
         to_cardinal = defines.direction.north,
         verify_forward = { end_dir = defines.direction.northeast, turn_dir = -1, count = 2 },
         verify_back = { end_dir = defines.direction.westsouthwest, turn_dir = 1, count = 1 },
      },
      [defines.direction.southeast] = {
         position = "upper-half", -- east-to-south
         from_cardinal = defines.direction.east,
         to_cardinal = defines.direction.south,
         verify_forward = { end_dir = defines.direction.southeast, turn_dir = 1, count = 2 },
         verify_back = { end_dir = defines.direction.westnorthwest, turn_dir = -1, count = 1 },
      },
      [defines.direction.south] = {
         position = "upper-half", -- west-to-north
         from_cardinal = defines.direction.west,
         to_cardinal = defines.direction.north,
         verify_forward = { end_dir = defines.direction.northnorthwest, turn_dir = 1, count = 1 },
         verify_back = { end_dir = defines.direction.southeast, turn_dir = -1, count = 2 },
      },
      [defines.direction.southwest] = {
         position = "upper-half", -- east-to-north
         from_cardinal = defines.direction.east,
         to_cardinal = defines.direction.north,
         verify_forward = { end_dir = defines.direction.northnortheast, turn_dir = -1, count = 1 },
         verify_back = { end_dir = defines.direction.southwest, turn_dir = 1, count = 2 },
      },
      [defines.direction.west] = {
         position = "upper-half", -- west-to-south
         from_cardinal = defines.direction.west,
         to_cardinal = defines.direction.south,
         verify_forward = { end_dir = defines.direction.southwest, turn_dir = -1, count = 2 },
         verify_back = { end_dir = defines.direction.eastnortheast, turn_dir = 1, count = 1 },
      },
      [defines.direction.northwest] = {
         position = "lower-half", -- west-to-north
         from_cardinal = defines.direction.west,
         to_cardinal = defines.direction.north,
         verify_forward = { end_dir = defines.direction.northwest, turn_dir = 1, count = 2 },
         verify_back = { end_dir = defines.direction.eastsoutheast, turn_dir = -1, count = 1 },
      },
   },
}
