-- Auto-generated by build_message_lists.py
-- DO NOT EDIT MANUALLY

local mod = {}

-- Set of valid message list names for O(1) lookup
mod.MESSAGE_LISTS = {
   ["blueprint-book-help"] = true,
   ["category-rows-help"] = true,
   ["crafting-menu-help"] = true,
   ["crafting-queue-help"] = true,
   ["debug-menu-help"] = true,
   ["decider-combinator"] = true,
   ["equipment-grid-help"] = true,
   ["general-ui-help"] = true,
   ["inventory-grid-help"] = true,
   ["map-help"] = true,
   ["menu-help"] = true,
   ["research-menu-help"] = true,
   ["research-queue-help"] = true,
   ["spidertron-remote-protohelp"] = true,
   ["trains-overview-help"] = true,
   ["warnings-menu-help"] = true,
}

mod.MESSAGE_LISTS_HASH = "0bb0ba258834ffa08b40d244127b0af06e8cd8eff4ddb8816a30b3249adb5fd5"

return mod
