-- Auto-generated by build_message_lists.py
-- DO NOT EDIT MANUALLY

local mod = {}

-- Set of valid message list names for O(1) lookup
mod.MESSAGE_LISTS = {
   ["blueprint-book-help"] = true,
   ["category-rows-help"] = true,
   ["ch1"] = true,
   ["ch10"] = true,
   ["ch2"] = true,
   ["ch3"] = true,
   ["ch4"] = true,
   ["ch5"] = true,
   ["ch6"] = true,
   ["ch7"] = true,
   ["ch8"] = true,
   ["ch9"] = true,
   ["crafting-menu-help"] = true,
   ["crafting-queue-help"] = true,
   ["debug-menu-help"] = true,
   ["decider-combinator"] = true,
   ["equipment-grid-help"] = true,
   ["general-ui-help"] = true,
   ["inventory-grid-help"] = true,
   ["map-help"] = true,
   ["menu-help"] = true,
   ["research-menu-help"] = true,
   ["research-queue-help"] = true,
   ["spidertron-remote-protohelp"] = true,
   ["trains-overview-help"] = true,
   ["warnings-menu-help"] = true,
}

mod.MESSAGE_LISTS_HASH = "707da2709e64e2d3e602fb21855f242304fb5fd931ad11cfd556bc70e1622438"

return mod
