on:
  push: {}
  pull_request: {}

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: 'stylua --check'
      shell: bash
      run: |
        cargo install --version 2.3.0 stylua --features lua52
        stylua --check . -v

